name: production-deploy

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy-production:
    uses: ./.github/workflows/deploy-step.yml
    with:
      environment: prod
      WEBHOOK_PATH: webhook-prod
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ vars.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GH_APP_ID: ${{ vars.PROD_GH_APP_ID }}
    secrets:
      GH_PRIVATE_KEY: ${{ secrets.PROD_GH_PRIVATE_KEY }}
      GH_WEBHOOK_SECRET: ${{ secrets.PROD_GH_WEBHOOK_SECRET }}
      CHAT_GPT_API_KEY: ${{ secrets.PROD_CHAT_GPT_API_KEY }}
